name: Feedback
description: "A question, issue or feedback on the OWASP Machine Learning Security Top 10 Project"
title: "[FEEDBACK]: "
labels: ["issues/general", "issues/triage"]
assignees:
  - shsingh
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to share your feedback!
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: "What type of feedback would you like to share with us?"
      options:
        - Documentation Issue Report
        - Website Issue Report
        - Suggestions for Improvement
        - General Feedback
        - Question
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: What would you like to report?
      description: If this is an issue, lso tell us what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I would like to report the following issue/feedback"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
